---
deployment:
  tasks:
    - echo "Starting deployment to Innovat6"
    - export DEPLOYPATH=/home/Innovat6/public_html
    # Copy all visible content
    - /bin/cp -rf * $DEPLOYPATH/
    # Copy hidden files (optional)
    - /bin/cp -rf .[^.]* $DEPLOYPATH/
    # Set permissions (optional)
    - /bin/chmod -R 755 $DEPLOYPATH/css
    - /bin/chmod -R 755 $DEPLOYPATH/js
    # Cleanup and verification
    - echo "Deployment completed at $(date)"
    - /bin/ls -la $DEPLOYPATH