deployment:
  tasks:
    - export DEPLOYPATH=/home/Innovat6/public_html
    - /bin/cp -r css $DEPLOYPATH/
    - /bin/cp -r file $DEPLOYPATH/
    - /bin/cp -r images $DEPLOYPATH/
    - /bin/cp -r js $DEPLOYPATH/
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp sitemap.xml $DEPLOYPATH/
