name: Deploy Static Site to cPanel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy static site via FTP
      - name: Deploy to server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.innovativestemhub.com
          username: innovative6@innovativestemhub.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: "./"
          server-dir: "/public_html/"
          exclude: |
            **/.git*
            **/.github/**
            **/README.md
          log-level: verbose