- name: FTP Deploy
  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    server: ${{ secrets.FTP_HOST }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    port: ${{ secrets.FTP_PORT }}
    protocol: ftp
    ftp-passive: true
    ftp-verbose: true
    timeout: 120000  # 2 minute timeout
    server-dir: ${{ secrets.FTP_REMOTE_DIR }}
    git-ftp-args: --insecure --all