name: FTP Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # or your specific build directory
        server-dir: /public_html/
        protocol: ftp      # Explicitly set to ftp (not sftp)
        ftp-passive: true  # Force passive mode
        ftp-verbose: true  # # or your remote directory