name: FTP Deploy (Minimal Working Version)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || '21' }}
          protocol: ftp
          local-dir: ./
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          security: passive  # This is the correct parameter for passive mode
          timeout: 120000    # 2 minute timeout
          log-level: debug   # For detailed error logging
          exclude: |
            .git/
            .github/
            .gitignore
            node_modules/
            .env