# name: Deploy to cPanel via FTP

# on:
#   push:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v4
      
#     - name: FTP Deploy
#       uses: SamKirkland/FTP-Deploy-Action@4.3.4  # Use specific version
#       with:
#         server: 
#         server-dir: /public_html/
#         exclude: |
#           .git*
#           .github/
#           README.md
#           *.env



on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.ftp_password }}